# Example from: https://hackmd.io/@bluegenes/BJPrrj7WB
# cluster_config.yml - cluster configuration
# For the actual available resources, see the cluster documentation:
# https://lisc.univie.ac.at/wiki/content/working_environment/services/computational_resources

__default__:
    time: 0-1:00:00
    nodes: 1
    cpus_per_task: 16
    mem: 128G
    output: log_snakemake_step-%j.out
    mail_type: FAIL,TIME_LIMIT
    gres: null # Should be null
    constraint: "hdd|ssd" # Dummy values, because it can't be empty

# Note: may need to push over to himem if the cluster is busy
preprocessing:
    mem: 120G
    cpus_per_task: 40

segmentation:
    mem: 256G
    cpus_per_task: 40

match_frame_pairs:
    gpus_per_node: 1
    mem: 128G
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

build_frame_objects:
    cpus_per_task: 20

postprocess_matches_to_tracklets:
    cpus_per_task: 1
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

combine_tracking_and_tracklets:
    cpus_per_task: 20

tracking:
    cpus_per_task: 16
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

barlow_tracking:
    cpus_per_task: 16
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"


# Behavior
subtract_background:
    mem: 4G
    cpus_per_task: 8

tiff2avi:
    cpus_per_task: 2

dlc_analyze_videos:
    cpus_per_task: 24
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

create_centerline:
    mem: 8G
    cpus_per_task: 4

normalize_img:
    mem: 4G
    cpus_per_task: 8

worm_unet:
    cpus_per_task: 24
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

sam2_segment:
    cpus_per_task: 24
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

coil_unet:
    cpus_per_task: 24
    gres: gpu:1
    constraint: "l40s|a30|t4|v100|l4"

binarize:
    cpus_per_task: 8
